version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  currency-api:
    depends_on:
      - redis
      - db
    restart: always
    build: .
    image: dayvsonsales/currency-api
    ports:
      - '3333:3333'
