version: '3.8'
services:
  db:
    container_name: currency-api-db
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'
  redis:
    container_name: currency-api-redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  currency-api:
    container_name: currency-api
    depends_on:
      - redis
      - db
    restart: always
    build: .
    image: dayvsonsales/currency-api
    ports:
      - '3333:3333'
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_RESET_TIME: 1800
      TYPEORM_SEEDING_FACTORIES: dist/src/infra/typeorm/database/factories/*.js
      TYPEORM_SEEDING_SEEDS: dist/src/infra/typeorm/database/seeders/*.js
volumes:
  db_data: {}
